spring:
  main:
    banner-mode: off

server:
  port: 8081
  servlet:
    context-path: /lesson7/api

springdoc:
  swagger-ui:
    path: /docs/swagger-ui.html
    defaultModelsExpandDepth: -1

from-name: ${FROM_NAME:lesson_7_name}
